### ISSUE TITLE
Authentication not working for https sites

### ISSUE THREAD

**Issue by gazben** [altrulife/cordova-create-react-app-example#1]
I've followed the tutorial, but even if I apply the patches, and set the `hostname`  in the `config.xml` the csrf/auth cookies are not sent up.

Server: `https://preview.<app>.com`
Cordova: `app://preview.<app>.com`

iOS version: 15.6
Xcode version: 13.4.1

I've set the `Access-Control-Allow-Origin` header to the exact origin and for GET requests it works. When I want to POST something the CSRF check will fail.

How did you get the https authentication to work in your production setup?

**Comment by bryan-hunter** [comment]
> I've followed the tutorial, but even if I apply the patches, and set the `hostname` in the `config.xml` the csrf/auth cookies are not sent up.
> 
> Server: `https://preview.<app>.com` Cordova: `app://preview.<app>.com`
> 
> iOS version: 15.6 Xcode version: 13.4.1
> 
> I've set the `Access-Control-Allow-Origin` header to the exact origin and for GET requests it works. When I want to POST something the CSRF check will fail.
> 
> How did you get the https authentication to work in your production setup?

Can you paste your `config.xml`?  I only use access tokens and not cookies, so maybe there is some other configuration needed to enable that.

**Comment by gazben** [comment]
I thought that you use cookies for the authentication because you even set the AppBoundDomains and the `limitsNavigationsToAppBoundDomains` is set to `YES`

According to the documentation: https://webkit.org/blog/10882/app-bound-domains/
I should get the cookies if the `limitsNavigationsToAppBoundDomains` is set.

A longer read on the issue: https://blog.merzlabs.com/posts/webview-history/

This is a redacted version of the `config.xml`:

```
<?xml version="1.0" encoding="utf-8"?>
<widget xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" id="com.app" version="1.0.0" android-versionCode="100000">
  <name>App Name</name>
  <content src="index.html"/>

  <preference name="ResolveServiceWorkerRequests" value="false"/>
  <preference name="KeepRunning" value="false"/>
  <preference name="SplashScreenDelay" value="1500"/>
  <preference name="AndroidLaunchMode" value="singleInstance"/>
  <preference name="AllowBackForwardNavigationGestures" value="true" />

  <access origin="*"/>
  <allow-intent href="https://*/*"/>
  <allow-intent href="tel:*"/>
  <allow-intent href="sms:*"/>
  <allow-intent href="mailto:*"/>

  <platform name="ios">

    <preference name="scheme" value="app" />
    <preference name="HostName" value="mobile.preview.app.eu" />

    <config-file target="*-Info.plist" parent="WKAppBoundDomains">
          <array>
              <!-- <string>{YOUR_DOMAIN}</string> -->
              <!-- <string>auth.{YOUR_DOMAIN}</string> -->
              <string>https://mobile.preview.app.eu</string>
              <string>mobile.preview.app.eu</string>
              <string>localhost</string>
          </array>
    </config-file>
    <preference name="LimitsNavigationsToAppBoundDomains" value="true" />
  </platform>

  <platform name="ios">
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/16.png" width="16" height="16" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/20.png" width="20" height="20" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/29.png" width="29" height="29" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/32.png" width="32" height="32" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/40.png" width="40" height="40" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/48.png" width="48" height="48" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/50.png" width="50" height="50" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/55.png" width="55" height="55" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/57.png" width="57" height="57" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/58.png" width="58" height="58" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/60.png" width="60" height="60" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/64.png" width="64" height="64" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/72.png" width="72" height="72" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/76.png" width="76" height="76" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/80.png" width="80" height="80" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/87.png" width="87" height="87" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/88.png" width="88" height="88" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/100.png" width="100" height="100" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/114.png" width="114" height="114" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/120.png" width="120" height="120" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/128.png" width="128" height="128" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/144.png" width="144" height="144" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/152.png" width="152" height="152" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/167.png" width="167" height="167" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/172.png" width="172" height="172" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/180.png" width="180" height="180" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/196.png" width="196" height="196" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/216.png" width="216" height="216" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/256.png" width="256" height="256" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/512.png" width="512" height="512" />
    <icon src="AppIcons/Assets.xcassets/AppIcon.appiconset/1024.png" width="1024" height="1024" />
  </platform>

  <!-- Misc permissions you may want in your app -->
  <platform name="ios">
      <config-file target="*-Info.plist" parent="NSCameraUsageDescription">
          <string>App needs the camera permission to scan the QR codes</string>
      </config-file>
  </platform>
</widget>
```

**Comment by bryan-hunter** [comment]
@gazben 
> limitsNavigationsToAppBoundDomains

I use this setting because otherwise we can't use serviceWorkers (navigator.serviceWorker is null without it).  And we use serviceWorkers for offline caching the app and getting new versions.

Here's a few differences I noticed, but this could just be because your setup is different or you tried the other stuff and this is where you landed when writing it:

I don't use either of these preferences: `scheme` and `HostName`
I do use `<content src="https://{MY_DOMAIN}" />` instead of "index.html" and this is where it loads the app from
I also don't prefix with `https` in `WKAppBoundDomains`, but I see you have both, so I image the 2nd would cover it, so probably not an issue.

I also know it's pretty tricky with Cordova to change settings sometimes because it might not overwrite an old one or merge properly, so when I get in a weird state, sometimes I have to blow away the whole project and redo the `cordova platform add` stuff

**Comment by gazben** [comment]
As it turns out my problem was that axios did not have the `withCredentials` flag.
The full solution in points:
 - limitsNavigationsToAppBoundDomains
 - allow origin from server
 - withCredentials in axios
